name: flutter_markdown_latex
description: A extension to render LaTeX in markdown for package flutter_markdown.
version: 0.3.4

publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  foyer_markdown:
    git: https://github.com/foyer-work/foyer_flutter_markdown
  flutter_math_fork: ^0.7.4
  markdown: ^7.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
