name: flutter_markdown_latex
description: A extension to render LaTeX in markdown for package flutter_markdown.
version: 0.3.4

publish_to: "none"

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  foyer_markdown:
    git: https://github.com/foyer-work/foyer_flutter_markdown
  flutter_math_fork: ^0.7.2
  markdown: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <6.0.0"
  golden_toolkit: ^0.15.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

